# Generated by Django 4.2.7 on 2023-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
